### ISSUE TITLE
Revision "Integrating the Brain Imaging Data Structure (BIDS) standard into C-PAC"

### ISSUE THREAD

**Issue by fabarrios** [Brainhack-Proceedings-2015/Solon-AMX-neuroview#1]
This report presents a customisable browser utility.

The text is not clear and requires an english revision, all the text changes are suggested, the authors should decide.
1. Leave only one section for Introduction and approach. The introduction needs to be rewritten a suggestion:
   " The amount of data acquired for an fMRI experiment dimension wise is very large and a challenge for neuroscience studies, in particular at data analysis and visualisation. There are different tools developed to address such massive data challenges, in particular the analysis needs for different protects may require new tools.  The goal of this Brainhack project is to build a flexible utility to analyse fMRI experimental results . . . "
2. Results; "NeuroView has bee created to support fMRI analysis, it has a modular design with three components or tools: . . . "
3. for the connectivity matrix.  can you give a cite for chord diagrams ?

**Comment by anibalsolon** [comment]
Hi @fabarrios , thank you for your review! I fixed the text, following your points.
It is, along with corrections from issue #3, the HEAD of this repository.

**Comment by fabarrios** [comment]
The revised version of the document addresses my concerns.  The document reads much better now.

**Comment by anibalsolon** [comment]
Thank you again, @fabarrios !

**Comment by fabarrios** [comment]
Thank you for revising the article.

Cheers
Fernando
