### ISSUE TITLE
Review from F. Xavier Castellanos

### ISSUE THREAD

**Issue by ccraddock** [Brainhack-Proceedings-2015/Solon-AMX-neuroview#3]
This abstract provides a cogent report on a product. A few minor grammatical problems are noted below (suggested replacement text is underlined):

Intro: “Different tools has been developed to oppose these challenges…” should be “tools **have** been developed to **confront** these challenges” 
The phrase “…but studies might have slight differences on analysis, that are not covered by such tools” is unclear.  I think the intent is:
**“Diverse tools have been developed to confront these challenges, but their analytical results can differ. Addressing those differences is not facilitated by existing tools.”**
Approach
“The goal of this Brainhack project **was to** build

3.1 “it is possible to search for **an** atlas region…” 
Conclusion
“This is **an** initial version…” 
“In our case study, NeuroView **facilitates** quick… and **promotes** discussion about them, since the results **will inform researchers about their data**.

“In **future** work, we aim to … and support some AFNI features, …” [delete ‘s after AFNI]

**Comment by anibalsolon** [comment]
I fixed the text based on the Castellanos' points! It is now the HEAD of this repository.

**Comment by nicholsn** [comment]
@anibalsolon thanks for updateing.

@ccraddock I have confirmed these suggestions have been incorporated.  Please feel free to close.

**Comment by anibalsolon** [comment]
Thank you, @nicholsn and @ccraddock !
